version: "3.9"

services:
  mongo:
    image: mongo:8
    container_name: inventory-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
